"""
    ReferenceTestResult

Result for one input generated by an executable [`@reference_test`](@ref).

`passed` is true when the reference and submission both return successfully and
their rendered outputs match.
"""
struct ReferenceTestResult
    function_name::Symbol
    visibility::Symbol
    index::Int
    input::String
    reference_output::String
    submission_output::String
    passed::Bool
    message::String
end

"""
    PropertyCheckResult

Result for one marked `@require` or `@forbid` property evaluated during grading.

`zero_marks` is true when a failed property should zero the whole assignment.
"""
struct PropertyCheckResult
    kind::Symbol
    visibility::Symbol
    points::Int
    description::String
    zero_marks::Bool
    passed::Bool
    message::String
end

"""
    CriterionResult

Per-criterion grading outcome for one rubric item.

`id` is the stable rubric identifier supplied by the teacher or generated from
the criterion. `awarded` is the number of marks awarded for this criterion.
"""
struct CriterionResult
    id::String
    kind::Symbol
    visibility::Symbol
    points::Int
    awarded::Int
    description::String
    passed::Bool
    message::String
    zero_marks::Bool
end

"""
    GradeResult

Result returned by [`grade_submission`](@ref).

Fields:
- `passed`, `exitcode`, `stdout`, `stderr` — overall pass/fail and process output.
- `student_id`, `student_report`, `html_report` — per-student feedback in Markdown and HTML.
- `csv_header`, `csv_row` — one-row CSV mark summary (`:default` format).
- `gradescope_json` — Gradescope autograder JSON (always populated; write via `gradescope_path`).
- `rubric_items`, `criterion_results`, `property_results`, `reference_test_results` — structured results.
- `awarded_by_category`, `possible_by_category`, `total_awarded`, `total_possible` — mark totals.
- `timed_out` — true when the submission test process exceeded `test_timeout_seconds`.
- `failure_category` — `:none`, `:load_failure`, `:test_failure`, `:timeout`, or `:zero_gate`.
- `failure_message` — human-readable explanation of the failure category.

# Example

```julia
julia> result = GradeResult(true, 0, "ok", "");

julia> isvalid(result)
true

julia> result.csv_header
"student_id,status,total"

julia> result.csv_row
",passed,0"
```
"""
struct GradeResult
    passed::Bool
    exitcode::Int
    stdout::String
    stderr::String
    student_id::String
    rubric_items::Vector{RubricItem}
    awarded_by_category::Dict{String, Int}
    possible_by_category::Dict{String, Int}
    total_awarded::Int
    total_possible::Int
    student_report::String
    csv_header::String
    csv_row::String
    reference_test_results::Vector{ReferenceTestResult}
    property_results::Vector{PropertyCheckResult}
    criterion_results::Vector{CriterionResult}
    timed_out::Bool
    failure_category::Symbol
    failure_message::String
    gradescope_json::String
    html_report::String
end

function GradeResult(passed::Bool, exitcode::Int, stdout::String, stderr::String)
    possible = Dict{String, Int}()
    awarded = Dict{String, Int}()
    total = 0
    header, row = _grade_csv(["student_id", "status", "total"], ["", passed ? "passed" : "failed", string(passed ? total : 0)])
    report = _student_grade_report("", passed, exitcode, RubricItem[], ReferenceTestResult[], PropertyCheckResult[], CriterionResult[], awarded, possible, passed ? total : 0, total, :none, "", stdout, stderr)
    html = _build_html_report(report, :none, "")
    gsj = _build_gradescope_json("", CriterionResult[], passed ? total : 0, total)
    return GradeResult(passed, exitcode, stdout, stderr, "", RubricItem[], awarded, possible, passed ? total : 0, total, report, header, row, ReferenceTestResult[], PropertyCheckResult[], CriterionResult[], false, :none, "", gsj, html)
end

Base.isvalid(result::GradeResult) = result.passed

function Base.show(io::IO, result::GradeResult)
    status = result.passed ? "passed" : "failed"
    print(io, "GradeResult(", status, ", exitcode=", result.exitcode, ")")
end

"""
    grade_submission(reference_path, submission_path; kwargs...)

Run the grading harness for a student submission package.

The harness runs the submission's tests in an isolated Julia process, then evaluates
any `@reference_test` entries and `@require`/`@forbid` property checks.

# Keywords

- `test_path` — alternate test file (default: `submission/test/runtests.jl`).
- `student_id` — identifier used in reports and CSV rows (default: `basename(submission_path)`).
- `report_path` — write Markdown report to this file when set.
- `html_path` — write HTML report to this file when set.
- `gradescope_path` — write Gradescope JSON to this file when set.
- `csv_path` — write CSV marks row to this file when set.
- `csv_format` — `:default`, `:canvas`, `:moodle`, or `:blackboard` (renames the student-id column).
- `append_csv` — append to `csv_path` rather than overwriting (default `true`).
- `test_timeout_seconds` — kill the submission test process after this many seconds (default `120`, `0` = no limit).
- `reference_timeout_seconds` — per-reference-test subprocess timeout (default `30`, `0` = no limit).

# Example

```julia
julia> result = grade_submission(
           "examples/SortingAssignment",
           "SortingAssignmentSubmission";
           student_id="s123",
           report_path="s123-feedback.md",
           csv_path="marks.csv",
       );

julia> result.csv_header
"student_id,status,hidden,public,total"

julia> result.csv_row
"s123,passed,4,3,7"

julia> startswith(result.student_report, "# Student Feedback Report")
true

julia> !isempty(result.html_report)
true

julia> !isempty(result.gradescope_json)
true
```
"""
function grade_submission(
    reference_path::AbstractString,
    submission_path::AbstractString;
    test_path=nothing,
    student_id::AbstractString=basename(abspath(submission_path)),
    report_path::Union{Nothing, AbstractString}=nothing,
    html_path::Union{Nothing, AbstractString}=nothing,
    gradescope_path::Union{Nothing, AbstractString}=nothing,
    csv_path::Union{Nothing, AbstractString}=nothing,
    csv_format::Symbol=:default,
    append_csv::Bool=true,
    test_timeout_seconds::Int=120,
    reference_timeout_seconds::Int=30,
)
    isdir(reference_path) || throw(ArgumentError("reference_path is not a directory"))
    isdir(submission_path) || throw(ArgumentError("submission_path is not a directory"))
    csv_format in (:default, :canvas, :moodle, :blackboard) ||
        throw(ArgumentError("unknown csv_format :$csv_format — choose :default, :canvas, :moodle, or :blackboard"))
    selected_test_path = test_path === nothing ? joinpath(submission_path, "test", "runtests.jl") : test_path
    isfile(selected_test_path) || throw(ArgumentError("test_path is not a file: $selected_test_path"))

    rubric, reference_specs = _collect_rubric_and_specs(reference_path)
    test_expr = "include($(repr(abspath(selected_test_path))))"
    cmd = `$(Base.julia_cmd()) --project=$(abspath(submission_path)) -e $test_expr`
    stdout_path = tempname()
    stderr_path = tempname()
    try
        proc, timed_out = _run_with_timeout(cmd, stdout_path, stderr_path; timeout_seconds=test_timeout_seconds)
        stdout_text = read(stdout_path, String)
        stderr_text = read(stderr_path, String)
        reference_results = _run_reference_tests(reference_path, submission_path, reference_specs; timeout_seconds=reference_timeout_seconds)
        property_results = _run_property_checks(submission_path, rubric)
        zeroed = any(result -> result.zero_marks && !result.passed, property_results)
        behavioral_passed = !timed_out && success(proc) && all(result -> result.passed, reference_results)
        passed = behavioral_passed && all(result -> result.passed || result.points == 0, property_results) && !zeroed
        criterion_results = _criterion_results(rubric, property_results, reference_results, behavioral_passed, zeroed)
        possible = _rubric_points_by_category(rubric)
        awarded = _awarded_points_by_category(rubric, criterion_results)
        total_possible = sum(values(possible); init=0)
        total_awarded = sum(values(awarded); init=0)
        categories = sort(collect(keys(possible)))
        header_values = vcat(["student_id", "status"], categories, ["total"])
        row_values = vcat([String(student_id), passed ? "passed" : "failed"], [string(get(awarded, category, 0)) for category in categories], [string(total_awarded)])
        header, row = _grade_csv(header_values, row_values)
        category, cat_message = _categorize_failure(proc.exitcode, stdout_text, stderr_text, timed_out, zeroed)
        report = _student_grade_report(String(student_id), passed, proc.exitcode, rubric, reference_results, property_results, criterion_results, awarded, possible, total_awarded, total_possible, category, cat_message, stdout_text, stderr_text)
        html = _build_html_report(report, category, cat_message)
        gsj = _build_gradescope_json(String(student_id), criterion_results, total_awarded, total_possible)
        result = GradeResult(passed, proc.exitcode, stdout_text, stderr_text, String(student_id), rubric, awarded, possible, total_awarded, total_possible, report, header, row, reference_results, property_results, criterion_results, timed_out, category, cat_message, gsj, html)
        report_path === nothing || write(report_path, report)
        html_path === nothing || write(html_path, html)
        gradescope_path === nothing || write(gradescope_path, gsj)
        if csv_path !== nothing
            lms_header, lms_row = _lms_csv(header, row, csv_format)
            _write_grade_csv(csv_path, lms_header, lms_row; append=append_csv)
        end
        return result
    finally
        rm(stdout_path; force=true)
        rm(stderr_path; force=true)
    end
end

function _run_property_checks(submission_path::AbstractString, rubric::Vector{RubricItem})
    project = _source_project_from_path(abspath(submission_path))
    results = PropertyCheckResult[]
    for item in rubric
        item.kind in (:require, :forbid) || continue
        item.spec === nothing && continue
        try
            holds = _property_holds(project, Main, item.spec)
            passed = item.kind == :require ? holds : !holds
            message = passed ? "property satisfied" : "property failed"
            push!(results, PropertyCheckResult(item.kind, item.visibility, item.points, item.description, item.zero_marks, passed, message))
        catch err
            push!(results, PropertyCheckResult(item.kind, item.visibility, item.points, item.description, item.zero_marks, false, sprint(showerror, err)))
        end
    end
    return results
end

function _run_reference_tests(reference_path::AbstractString, submission_path::AbstractString, specs::Vector{ReferenceTestSpec}; timeout_seconds::Int=30)
    isempty(specs) && return ReferenceTestResult[]
    results = ReferenceTestResult[]
    for spec in specs
        reference_values = _evaluate_reference_spec(reference_path, spec, :teacher; timeout_seconds=timeout_seconds)
        submission_values = _evaluate_reference_spec(submission_path, spec, :student; timeout_seconds=timeout_seconds)
        n = max(length(reference_values), length(submission_values))
        for index in 1:n
            ref = index <= length(reference_values) ? reference_values[index] : (ok=false, input="", output="", error="missing reference result")
            sub = index <= length(submission_values) ? submission_values[index] : (ok=false, input=get(ref, :input, ""), output="", error="missing submission result")
            input = get(ref, :input, get(sub, :input, ""))
            passed = ref.ok && sub.ok && ref.output == sub.output
            message = if passed
                "matched reference output"
            elseif !ref.ok
                "reference errored: $(ref.error)"
            elseif !sub.ok
                "submission errored: $(sub.error)"
            else
                "expected $(ref.output), got $(sub.output)"
            end
            push!(results, ReferenceTestResult(spec.function_name, spec.visibility, index, input, ref.output, sub.output, passed, message))
        end
    end
    return results
end

function _evaluate_reference_spec(package_path::AbstractString, spec::ReferenceTestSpec, mode::Symbol; timeout_seconds::Int=30)
    output_path = tempname()
    script_path = tempname() * ".jl"
    stderr_path = tempname()
    write(script_path, _reference_eval_script())
    active_project = Base.active_project()
    grader_project = active_project === nothing ? "" : dirname(active_project)
    cmd = `$(Base.julia_cmd()) --project=$(abspath(package_path)) $(script_path) $(abspath(package_path)) $(String(spec.function_name)) $(spec.input_expr) $(output_path) $(String(mode)) $(grader_project)`
    try
        proc, timed_out = _run_with_timeout(cmd, devnull, stderr_path; timeout_seconds=timeout_seconds)
        if timed_out
            return [(ok=false, input="", output="", error="reference test timed out after $(timeout_seconds)s")]
        end
        if success(proc) && isfile(output_path)
            return open(deserialize, output_path)
        end
        err = isfile(stderr_path) ? strip(read(stderr_path, String)) : ""
        isempty(err) && (err = "reference-test process failed")
        return [(ok=false, input="", output="", error=err)]
    finally
        rm(output_path; force=true)
        rm(script_path; force=true)
        rm(stderr_path; force=true)
    end
end

"""
    _reference_eval_script()

Return the source text of a self-contained Julia script that is written to a temp file
and run in a fresh process by `_evaluate_reference_spec`. The script loads the target
package via `include_string` (stripping annotations first), evaluates the named function
on each generated input, and serializes a `Vector{NamedTuple}` of results to `output_path`.

Running in a separate process avoids module-name collisions between the reference package
and the submission package, and prevents student code from affecting the grader's state.
"""
function _reference_eval_script()
    return raw"""
using Serialization
using TOML

function _project_name(path::AbstractString)
    project = joinpath(path, "Project.toml")
    isfile(project) || error("Project.toml not found in " * path)
    data = TOML.parsefile(project)
    return String(get(data, "name", basename(path)))
end

function _call_with_input(f, input)
    input isa Tuple && return f(input...)
    return f(input)
end

function _collect_block(lines::AbstractVector, start_i::Int)
    body = String[]
    depth = 1
    i = start_i + 1
    while i <= length(lines)
        s = strip(lines[i])
        if endswith(s, " begin") || occursin(r"\bbegin\b", s)
            depth += count(==("begin"), split(s))
        end
        if s == "end"
            depth -= 1
            depth == 0 && return body, i
        end
        push!(body, lines[i])
        i += 1
    end
    error("unterminated annotation block beginning at line " * string(start_i))
end

function _keep_body(macro_name::AbstractString, mode::AbstractString)
    if mode == "student"
        return macro_name in ("@scaffolding", "@student_test")
    else
        return macro_name in ("@solution", "@student_test", "@hidden_test")
    end
end

function _loadable_source(text::AbstractString, mode::AbstractString)
    lines = split(text, '\n'; keepempty=true)
    out = String[]
    i = 1
    while i <= length(lines)
        stripped = strip(lines[i])
        if occursin(r"^(using|import)\s+SkeletonizePackage\b", stripped)
            i += 1
            continue
        elseif stripped in ("@solution begin", "@scaffolding begin", "@student_test begin", "@hidden_test begin")
            macro_name = split(stripped)[1]
            block, j = _collect_block(lines, i)
            _keep_body(macro_name, mode) && append!(out, block)
            i = j + 1
        else
            push!(out, lines[i])
            i += 1
        end
    end
    return join(out, "\n")
end

package_path = ARGS[1]
function_name = Symbol(ARGS[2])
input_expr = ARGS[3]
output_path = ARGS[4]
mode = ARGS[5]
grader_project = ARGS[6]
isempty(grader_project) || push!(LOAD_PATH, grader_project)
module_name = Symbol(_project_name(package_path))
source_path = joinpath(package_path, "src", string(module_name) * ".jl")
source = _loadable_source(read(source_path, String), mode)
include_string(Main, source, source_path)
mod = getfield(Main, module_name)
f = getfield(mod, function_name)
inputs = collect(eval(Meta.parse(input_expr)))
results = NamedTuple[]
for input in inputs
    try
        output = _call_with_input(f, input)
        push!(results, (ok=true, input=repr(input), output=repr(output), error=""))
    catch err
        push!(results, (ok=false, input=repr(input), output="", error=sprint(showerror, err)))
    end
end
serialize(output_path, results)
"""
end

# Extract the function name from a reference-test rubric item description such as
# "reference behaviour `foo generator=1:10`". Returns nothing if the pattern
# does not match (fallback: match all results with the same visibility).
function _reference_test_fn_name(description::AbstractString)
    m = match(r"^reference behaviour `([A-Za-z_]\w*)\b", description)
    m === nothing && return nothing
    return Symbol(m.captures[1])
end

function _rubric_points_by_category(items::Vector{RubricItem})
    points = Dict{String, Int}()
    for item in items
        item.kind in (:marks, :require, :forbid) || continue
        category = String(item.visibility)
        points[category] = get(points, category, 0) + item.points
    end
    return points
end

function _criterion_results(rubric::Vector{RubricItem}, property_results::Vector{PropertyCheckResult}, reference_results::Vector{ReferenceTestResult}, behavioral_passed::Bool, zeroed::Bool)
    results = CriterionResult[]
    property_queue = copy(property_results)
    for item in rubric
        if item.kind == :marks
            passed = behavioral_passed && !zeroed
            awarded = passed ? item.points : 0
            message = zeroed ? "assignment zeroed by a gating requirement" : passed ? "behavioural tests passed" : "behavioural tests failed"
            push!(results, CriterionResult(item.id, item.kind, item.visibility, item.points, awarded, item.description, passed, message, item.zero_marks))
        elseif item.kind in (:require, :forbid)
            result = isempty(property_queue) ? nothing : popfirst!(property_queue)
            passed = result !== nothing && result.passed && !zeroed
            awarded = passed ? item.points : 0
            message = result === nothing ? "property was not evaluated" : result.message
            zeroed && (message = "assignment zeroed by a gating requirement")
            push!(results, CriterionResult(item.id, item.kind, item.visibility, item.points, awarded, item.description, passed, message, item.zero_marks))
        elseif item.kind == :reference_test
            fn = _reference_test_fn_name(item.description)
            related = [r for r in reference_results
                       if r.visibility == item.visibility &&
                          (fn === nothing || r.function_name == fn)]
            passed = !isempty(related) && all(result -> result.passed, related)
            message = isempty(related) ? "reference test metadata only" : passed ? "all generated inputs matched" : "one or more generated inputs failed"
            push!(results, CriterionResult(item.id, item.kind, item.visibility, item.points, 0, item.description, passed, message, item.zero_marks))
        end
    end
    return results
end

function _awarded_points_by_category(rubric::Vector{RubricItem}, criterion_results::Vector{CriterionResult})
    possible = _rubric_points_by_category(rubric)
    awarded = Dict(category => 0 for category in keys(possible))
    for result in criterion_results
        result.kind in (:marks, :require, :forbid) || continue
        category = String(result.visibility)
        awarded[category] = get(awarded, category, 0) + result.awarded
    end
    return awarded
end

function _student_grade_report(student_id::AbstractString, passed::Bool, exitcode::Int, rubric::Vector{RubricItem}, reference_results::Vector{ReferenceTestResult}, property_results::Vector{PropertyCheckResult}, criterion_results::Vector{CriterionResult}, awarded::Dict{String, Int}, possible::Dict{String, Int}, total_awarded::Int, total_possible::Int, failure_category::Symbol, failure_message::AbstractString, stdout::String, stderr::String)
    io = IOBuffer()
    println(io, "# Student Feedback Report")
    println(io)
    isempty(student_id) || println(io, "Student: `", student_id, "`")
    println(io, "Status: ", passed ? "passed" : "failed")
    if failure_category != :none
        println(io, "Failure: **", failure_category, "** — ", failure_message)
    end
    println(io, "Exit code: ", exitcode)
    println(io, "Total: ", total_awarded, " / ", total_possible, " marks")
    println(io)
    println(io, "## Mark Summary")
    categories = sort(collect(keys(possible)))
    if isempty(categories)
        println(io)
        println(io, "No marked rubric criteria were found in the reference package.")
    else
        println(io)
        for category in categories
            println(io, "- ", category, ": ", get(awarded, category, 0), " / ", possible[category])
        end
    end
    println(io)
    println(io, "## Rubric Results")
    marked_results = [result for result in criterion_results if result.kind in (:marks, :require, :forbid)]
    if isempty(marked_results)
        println(io)
        println(io, "No marked criteria were available.")
    else
        for result in marked_results
            println(io)
            zero_note = result.zero_marks ? " Zeroes assignment if failed." : ""
            println(io, "- `", result.id, "` [", result.visibility, "] ", result.description, ": ", result.awarded, " / ", result.points, " mark", result.points == 1 ? "" : "s", ". ", result.message, ".", zero_note)
        end
    end
    properties = [item for item in rubric if item.kind != :marks]
    if !isempty(properties)
        println(io)
        println(io, "## Code Properties")
        property_queue = copy(property_results)
        for item in properties
            println(io)
            if item.kind in (:require, :forbid) && !isempty(property_queue)
                result = popfirst!(property_queue)
                status = result.passed ? "passed" : "failed"
                points = result.passed ? result.points : 0
                zero_note = result.zero_marks ? " Zeroes assignment if failed." : ""
                println(io, "- [", result.visibility, "] ", status, ": ", result.description, " (", points, " / ", result.points, " marks).", zero_note)
            else
                println(io, "- [", item.visibility, "] ", item.description)
            end
        end
    end
    if !isempty(reference_results)
        println(io)
        println(io, "## Reference Tests")
        for result in reference_results
            status = result.passed ? "passed" : "failed"
            println(io)
            println(io, "- [", result.visibility, "] `", result.function_name, "` input ", result.index, " ", status, ": ", result.message)
        end
    end
    println(io)
    println(io, "## Test Output")
    if isempty(strip(stdout)) && isempty(strip(stderr))
        println(io)
        println(io, "No test output was captured.")
    else
        if !isempty(strip(stdout))
            println(io)
            println(io, "### stdout")
            println(io)
            println(io, "```text")
            print(io, rstrip(stdout))
            println(io)
            println(io, "```")
        end
        if !isempty(strip(stderr))
            println(io)
            println(io, "### stderr")
            println(io)
            println(io, "```text")
            print(io, rstrip(stderr))
            println(io)
            println(io, "```")
        end
    end
    return String(take!(io))
end

function _grade_csv(header_values::Vector{String}, row_values::Vector{String})
    header = join(_csv_escape.(header_values), ",")
    row = join(_csv_escape.(row_values), ",")
    return header, row
end

function _csv_escape(value::AbstractString)
    needs_quotes = any(ch -> ch in (',', '"', '\n', '\r'), value)
    escaped = replace(value, "\"" => "\"\"")
    return needs_quotes ? "\"$escaped\"" : escaped
end

function _write_grade_csv(path::AbstractString, header::AbstractString, row::AbstractString; append::Bool)
    should_write_header = !append || !isfile(path) || filesize(path) == 0
    open(path, append ? "a" : "w") do io
        should_write_header && println(io, header)
        println(io, row)
    end
    return path
end

# ── Timeout helper ────────────────────────────────────────────────────────────

"""
    _run_with_timeout(cmd, stdout_path, stderr_path; timeout_seconds) -> (proc, timed_out)

Spawn `cmd` and wait up to `timeout_seconds` for it to finish. If the process exceeds
the limit it is killed and `timed_out` is returned as `true`. Pass `timeout_seconds=0`
to wait indefinitely.
"""
function _run_with_timeout(cmd, stdout_path, stderr_path; timeout_seconds::Int)
    proc = run(pipeline(cmd; stdout=stdout_path, stderr=stderr_path); wait=false)
    if timeout_seconds > 0
        status = timedwait(() -> process_exited(proc), float(timeout_seconds))
        if status == :timed_out
            kill(proc)
            wait(proc)
            return proc, true
        end
    else
        wait(proc)
    end
    return proc, false
end

# ── Failure categorisation ────────────────────────────────────────────────────

"""
    _categorize_failure(exitcode, stdout, stderr, timed_out, zeroed) -> (category, message)

Classify why grading failed from process outputs and flags.
"""
function _categorize_failure(exitcode::Int, stdout::String, stderr::String, timed_out::Bool, zeroed::Bool)
    timed_out  && return (:timeout,      "submission tests timed out")
    zeroed     && return (:zero_gate,    "a zero_marks=true requirement failed")
    exitcode == 0 && return (:none, "")
    combined = stdout * stderr
    if occursin(r"Package .* not found|cannot find package|not found in current path"i, combined)
        return (:load_failure, "package not found — check Project.toml dependencies")
    end
    if occursin(r"Test Failed|Some tests did not pass"i, combined)
        return (:test_failure, "tests failed with exit code $exitcode")
    end
    if occursin(r"LoadError|ParseError|syntax: |UndefVarError.*top-level"i, stderr)
        return (:load_failure, _first_error_line(stderr))
    end
    return (:test_failure, "tests failed with exit code $exitcode")
end

function _first_error_line(text::AbstractString)
    for line in split(text, '\n')
        s = strip(line)
        isempty(s) && continue
        (startswith(s, "ERROR") || startswith(s, "LoadError") || startswith(s, "ParseError")) && return s
    end
    nonempty = filter(!isempty ∘ strip, split(text, '\n'))
    return isempty(nonempty) ? "" : strip(first(nonempty))
end

# ── JSON helpers ──────────────────────────────────────────────────────────────

function _json_string(s::AbstractString)
    # Full RFC 8259 §7 escaping: backslash, quote, and all control chars U+0000–U+001F.
    io = IOBuffer()
    write(io, '"')
    for c in s
        if     c == '\\'  ; write(io, "\\\\")
        elseif c == '"'   ; write(io, "\\\"")
        elseif c == '\n'  ; write(io, "\\n")
        elseif c == '\r'  ; write(io, "\\r")
        elseif c == '\t'  ; write(io, "\\t")
        elseif UInt32(c) < 0x20; write(io, "\\u", lpad(string(UInt32(c); base=16), 4, '0'))
        else              ; write(io, c)
        end
    end
    write(io, '"')
    return String(take!(io))
end

"""
    _build_gradescope_json(student_id, criterion_results, total_awarded, total_possible) -> String

Build a Gradescope autograder JSON string without requiring an external JSON package.
Spec: https://gradescope-autograders.readthedocs.io/en/latest/specs/
"""
function _build_gradescope_json(student_id::AbstractString, criterion_results::Vector{CriterionResult}, total_awarded::Int, total_possible::Int)
    io = IOBuffer()
    println(io, "{")
    println(io, "  \"score\": ", total_awarded, ",")
    println(io, "  \"max_score\": ", total_possible, ",")
    println(io, "  \"output\": ", _json_string("Student: $student_id"), ",")
    println(io, "  \"visibility\": \"after_published\",")
    print(io,   "  \"tests\": [")
    tests = [r for r in criterion_results if r.kind in (:marks, :require, :forbid)]
    if isempty(tests)
        println(io, "]")
    else
        println(io)
        for (i, result) in enumerate(tests)
            comma = i < length(tests) ? "," : ""
            vis = result.visibility == :public ? "visible" : "after_published"
            println(io, "    {")
            println(io, "      \"score\": ", result.awarded, ",")
            println(io, "      \"max_score\": ", result.points, ",")
            println(io, "      \"name\": ", _json_string(result.description), ",")
            println(io, "      \"number\": ", _json_string(result.id), ",")
            println(io, "      \"visibility\": ", _json_string(vis), ",")
            println(io, "      \"status\": ", _json_string(result.passed ? "passed" : "failed"))
            println(io, "    }", comma)
        end
        println(io, "  ]")
    end
    print(io, "}")
    return String(take!(io))
end

# ── HTML report helpers ───────────────────────────────────────────────────────

function _html_escape(s::AbstractString)
    s = replace(s, "&" => "&amp;", "<" => "&lt;", ">" => "&gt;")
    return s
end

# Convert inline backtick spans and **bold** to HTML; HTML-escape everything else.
# Unmatched backticks (odd count) fall back to plain HTML-escaped text.
function _fmt_inline(text::AbstractString)
    parts = split(text, '`')
    # An even number of parts means an odd number of backticks — no proper pair.
    iseven(length(parts)) && return _html_escape(text)
    io = IOBuffer()
    for (i, part) in enumerate(parts)
        if isodd(i)
            escaped = _html_escape(part)
            write(io, replace(escaped, r"\*\*([^*]+)\*\*" => s -> "<strong>$(s[3:end-2])</strong>"))
        else
            write(io, "<code>", _html_escape(part), "</code>")
        end
    end
    return String(take!(io))
end

"""
    _build_html_report(markdown_report, failure_category, failure_message) -> String

Convert a Markdown-format student report to a self-contained HTML document with
inline CSS. The conversion handles headings, bullet lists, fenced code blocks,
and inline backtick spans.
"""
function _build_html_report(markdown_report::AbstractString, failure_category::Symbol, failure_message::AbstractString)
    io_body = IOBuffer()
    in_pre = false
    in_ul  = false
    for raw_line in split(markdown_report, '\n')
        if !in_pre && startswith(raw_line, "```")
            in_ul && (println(io_body, "</ul>"); in_ul = false)
            println(io_body, "<pre>"); in_pre = true; continue
        end
        if in_pre && startswith(raw_line, "```")
            println(io_body, "</pre>"); in_pre = false; continue
        end
        if in_pre; println(io_body, _html_escape(raw_line)); continue; end
        if startswith(raw_line, "### ")
            in_ul && (println(io_body, "</ul>"); in_ul = false)
            println(io_body, "<h3>", _fmt_inline(raw_line[5:end]), "</h3>")
        elseif startswith(raw_line, "## ")
            in_ul && (println(io_body, "</ul>"); in_ul = false)
            println(io_body, "<h2>", _fmt_inline(raw_line[4:end]), "</h2>")
        elseif startswith(raw_line, "# ")
            in_ul && (println(io_body, "</ul>"); in_ul = false)
            println(io_body, "<h1>", _fmt_inline(raw_line[3:end]), "</h1>")
        elseif startswith(raw_line, "- ")
            in_ul || (println(io_body, "<ul>"); in_ul = true)
            println(io_body, "<li>", _fmt_inline(raw_line[3:end]), "</li>")
        elseif isempty(strip(raw_line))
            in_ul && (println(io_body, "</ul>"); in_ul = false)
        else
            in_ul && (println(io_body, "</ul>"); in_ul = false)
            println(io_body, "<p>", _fmt_inline(raw_line), "</p>")
        end
    end
    in_ul && println(io_body, "</ul>")
    in_pre && println(io_body, "</pre>")  # close any unterminated fenced code block

    banner = failure_category == :none ? "" :
        "<div class=\"failure-banner\"><strong>$(uppercase(string(failure_category)))</strong>: $(_html_escape(String(failure_message)))</div>\n"
    body = String(take!(io_body))

    return """<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Student Feedback</title>
<style>
body{font-family:sans-serif;max-width:860px;margin:2em auto;padding:0 1em;color:#222}
h1{border-bottom:2px solid #444;padding-bottom:.3em}
h2{margin-top:1.5em;border-bottom:1px solid #ddd;padding-bottom:.2em}
h3{margin-top:1em}
.failure-banner{background:#fde;border:1px solid #c88;padding:.5em 1em;border-radius:4px;margin:1em 0;font-size:.95em}
ul{margin:.3em 0;padding-left:1.5em}
li{margin:.15em 0}
code{background:#f0f0f0;padding:0 .25em;border-radius:2px;font-family:monospace;font-size:.93em}
pre{background:#f4f4f4;padding:.8em;overflow-x:auto;border-radius:4px;font-size:.9em;white-space:pre-wrap}
</style>
</head>
<body>
$(banner)$(body)
</body>
</html>"""
end

# ── LMS CSV format helper ─────────────────────────────────────────────────────

"""
    _lms_csv(header, row, format) -> (header, row)

Return `(header, row)` with the `student_id` column renamed per LMS convention.
`:default` leaves both unchanged; `:canvas` renames to `SIS Login ID`;
`:moodle` to `username`; `:blackboard` to `Username`.
"""
function _lms_csv(header::AbstractString, row::AbstractString, format::Symbol)
    format == :default && return header, row
    rename_map = Dict(:canvas => "SIS Login ID", :moodle => "username", :blackboard => "Username")
    haskey(rename_map, format) || throw(ArgumentError("unknown csv_format :$format — choose :default, :canvas, :moodle, or :blackboard"))
    parts = split(header, ","; limit=2)
    new_header = length(parts) == 2 ? _csv_escape(rename_map[format]) * "," * parts[2] : _csv_escape(rename_map[format])
    return new_header, row
end
