"""
    ReferenceTestResult

Result for one input generated by an executable [`@reference_test`](@ref).

`passed` is true when the reference and submission both return successfully and
their rendered outputs match.
"""
struct ReferenceTestResult
    function_name::Symbol
    visibility::Symbol
    index::Int
    input::String
    reference_output::String
    submission_output::String
    passed::Bool
    message::String
end

"""
    PropertyCheckResult

Result for one marked `@require` or `@forbid` property evaluated during grading.

`zero_marks` is true when a failed property should zero the whole assignment.
"""
struct PropertyCheckResult
    kind::Symbol
    visibility::Symbol
    points::Int
    description::String
    zero_marks::Bool
    passed::Bool
    message::String
end

"""
    CriterionResult

Per-criterion grading outcome for one rubric item.

`id` is the stable rubric identifier supplied by the teacher or generated from
the criterion. `awarded` is the number of marks awarded for this criterion.
"""
struct CriterionResult
    id::String
    kind::Symbol
    visibility::Symbol
    points::Int
    awarded::Int
    description::String
    passed::Bool
    message::String
    zero_marks::Bool
end

"""
    GradeResult

Result returned by [`grade_submission`](@ref).

# Example

```julia
julia> result = GradeResult(true, 0, "ok", "");

julia> isvalid(result)
true

julia> result.csv_header
"student_id,status,total"

julia> result.csv_row
",passed,0"
```
"""
struct GradeResult
    passed::Bool
    exitcode::Int
    stdout::String
    stderr::String
    student_id::String
    rubric_items::Vector{RubricItem}
    awarded_by_category::Dict{String, Int}
    possible_by_category::Dict{String, Int}
    total_awarded::Int
    total_possible::Int
    student_report::String
    csv_header::String
    csv_row::String
    reference_test_results::Vector{ReferenceTestResult}
    property_results::Vector{PropertyCheckResult}
    criterion_results::Vector{CriterionResult}
end

function GradeResult(passed::Bool, exitcode::Int, stdout::String, stderr::String)
    possible = Dict{String, Int}()
    awarded = Dict{String, Int}()
    total = 0
    header, row = _grade_csv(["student_id", "status", "total"], ["", passed ? "passed" : "failed", string(passed ? total : 0)])
    report = _student_grade_report("", passed, exitcode, RubricItem[], ReferenceTestResult[], PropertyCheckResult[], CriterionResult[], awarded, possible, passed ? total : 0, total, stdout, stderr)
    return GradeResult(passed, exitcode, stdout, stderr, "", RubricItem[], awarded, possible, passed ? total : 0, total, report, header, row, ReferenceTestResult[], PropertyCheckResult[], CriterionResult[])
end

Base.isvalid(result::GradeResult) = result.passed

function Base.show(io::IO, result::GradeResult)
    status = result.passed ? "passed" : "failed"
    print(io, "GradeResult(", status, ", exitcode=", result.exitcode, ")")
end

"""
    grade_submission(reference_path, submission_path; test_path=nothing, student_id=basename(submission_path), report_path=nothing, csv_path=nothing, append_csv=true)

Run the first-pass grading harness for a student submission package.

The current harness checks that `reference_path` and `submission_path` are
package directories, then runs the submission tests in an isolated Julia
process. `test_path` may point to an alternate test file.

Any `@reference_test f generator=...` or `@reference_test f inputs=...` entries
in the reference package are then executed by running the reference and
submission packages in separate Julia processes. This avoids module-name
collisions and lets the grader compare the submitted function against the
teacher's reference implementation.

The result includes two grading outputs:

- `student_report`, a Markdown report intended for student feedback.
- `csv_header` and `csv_row`, a CSV-friendly mark summary suitable for
  concatenating one row per student.

The result records both category totals and per-criterion outcomes. Ordinary
`@marks` criteria are awarded when the submission tests and executable reference
tests pass. Marked `@require` and `@forbid` criteria are awarded independently,
unless a failed `zero_marks=true` criterion zeros the whole assignment.

# Example

```julia
julia> result = grade_submission(
           "examples/SortingAssignment",
           "SortingAssignmentSubmission";
           student_id="s123",
           report_path="s123-feedback.md",
           csv_path="marks.csv",
       );

julia> result.csv_header
"student_id,status,hidden,public,total"

julia> result.csv_row
"s123,passed,4,3,7"

julia> startswith(result.student_report, "# Student Feedback Report")
true
```

When the submission tests fail, the same fields are still populated:

```julia
julia> result.passed
false

julia> result.total_awarded
0
```
"""
function grade_submission(reference_path::AbstractString, submission_path::AbstractString; test_path=nothing, student_id::AbstractString=basename(abspath(submission_path)), report_path::Union{Nothing, AbstractString}=nothing, csv_path::Union{Nothing, AbstractString}=nothing, append_csv::Bool=true)
    isdir(reference_path) || throw(ArgumentError("reference_path is not a directory"))
    isdir(submission_path) || throw(ArgumentError("submission_path is not a directory"))
    selected_test_path = test_path === nothing ? joinpath(submission_path, "test", "runtests.jl") : test_path
    isfile(selected_test_path) || throw(ArgumentError("test_path is not a file: $selected_test_path"))

    rubric, reference_specs = _collect_rubric_and_specs(reference_path)
    test_expr = "include($(repr(abspath(selected_test_path))))"
    cmd = `$(Base.julia_cmd()) --project=$(abspath(submission_path)) -e $test_expr`
    stdout_path = tempname()
    stderr_path = tempname()
    try
        proc = run(pipeline(cmd; stdout=stdout_path, stderr=stderr_path); wait=false)
        wait(proc)
        stdout = read(stdout_path, String)
        stderr = read(stderr_path, String)
        reference_results = _run_reference_tests(reference_path, submission_path, reference_specs)
        property_results = _run_property_checks(submission_path, rubric)
        zeroed = any(result -> result.zero_marks && !result.passed, property_results)
        behavioral_passed = success(proc) && all(result -> result.passed, reference_results)
        passed = behavioral_passed && all(result -> result.passed || result.points == 0, property_results) && !zeroed
        criterion_results = _criterion_results(rubric, property_results, reference_results, behavioral_passed, zeroed)
        possible = _rubric_points_by_category(rubric)
        awarded = _awarded_points_by_category(rubric, criterion_results)
        total_possible = sum(values(possible); init=0)
        total_awarded = sum(values(awarded); init=0)
        categories = sort(collect(keys(possible)))
        header_values = vcat(["student_id", "status"], categories, ["total"])
        row_values = vcat([String(student_id), passed ? "passed" : "failed"], [string(get(awarded, category, 0)) for category in categories], [string(total_awarded)])
        header, row = _grade_csv(header_values, row_values)
        report = _student_grade_report(String(student_id), passed, proc.exitcode, rubric, reference_results, property_results, criterion_results, awarded, possible, total_awarded, total_possible, stdout, stderr)
        result = GradeResult(passed, proc.exitcode, stdout, stderr, String(student_id), rubric, awarded, possible, total_awarded, total_possible, report, header, row, reference_results, property_results, criterion_results)
        report_path === nothing || write(report_path, report)
        csv_path === nothing || _write_grade_csv(csv_path, header, row; append=append_csv)
        return result
    finally
        rm(stdout_path; force=true)
        rm(stderr_path; force=true)
    end
end

function _run_property_checks(submission_path::AbstractString, rubric::Vector{RubricItem})
    project = _source_project_from_path(abspath(submission_path))
    results = PropertyCheckResult[]
    for item in rubric
        item.kind in (:require, :forbid) || continue
        item.spec === nothing && continue
        try
            holds = _property_holds(project, Main, item.spec)
            passed = item.kind == :require ? holds : !holds
            message = passed ? "property satisfied" : "property failed"
            push!(results, PropertyCheckResult(item.kind, item.visibility, item.points, item.description, item.zero_marks, passed, message))
        catch err
            push!(results, PropertyCheckResult(item.kind, item.visibility, item.points, item.description, item.zero_marks, false, sprint(showerror, err)))
        end
    end
    return results
end

function _run_reference_tests(reference_path::AbstractString, submission_path::AbstractString, specs::Vector{ReferenceTestSpec})
    isempty(specs) && return ReferenceTestResult[]
    results = ReferenceTestResult[]
    for spec in specs
        reference_values = _evaluate_reference_spec(reference_path, spec, :teacher)
        submission_values = _evaluate_reference_spec(submission_path, spec, :student)
        n = max(length(reference_values), length(submission_values))
        for index in 1:n
            ref = index <= length(reference_values) ? reference_values[index] : (ok=false, input="", output="", error="missing reference result")
            sub = index <= length(submission_values) ? submission_values[index] : (ok=false, input=get(ref, :input, ""), output="", error="missing submission result")
            input = get(ref, :input, get(sub, :input, ""))
            passed = ref.ok && sub.ok && ref.output == sub.output
            message = if passed
                "matched reference output"
            elseif !ref.ok
                "reference errored: $(ref.error)"
            elseif !sub.ok
                "submission errored: $(sub.error)"
            else
                "expected $(ref.output), got $(sub.output)"
            end
            push!(results, ReferenceTestResult(spec.function_name, spec.visibility, index, input, ref.output, sub.output, passed, message))
        end
    end
    return results
end

function _evaluate_reference_spec(package_path::AbstractString, spec::ReferenceTestSpec, mode::Symbol)
    output_path = tempname()
    script_path = tempname() * ".jl"
    stderr_path = tempname()
    write(script_path, _reference_eval_script())
    active_project = Base.active_project()
    grader_project = active_project === nothing ? "" : dirname(active_project)
    cmd = `$(Base.julia_cmd()) --project=$(abspath(package_path)) $(script_path) $(abspath(package_path)) $(String(spec.function_name)) $(spec.input_expr) $(output_path) $(String(mode)) $(grader_project)`
    try
        proc = run(pipeline(cmd; stdout=devnull, stderr=stderr_path); wait=false)
        wait(proc)
        if success(proc) && isfile(output_path)
            return open(deserialize, output_path)
        end
        err = isfile(stderr_path) ? strip(read(stderr_path, String)) : ""
        isempty(err) && (err = "reference-test process failed")
        return [(ok=false, input="", output="", error=err)]
    finally
        rm(output_path; force=true)
        rm(script_path; force=true)
        rm(stderr_path; force=true)
    end
end

"""
    _reference_eval_script()

Return the source text of a self-contained Julia script that is written to a temp file
and run in a fresh process by `_evaluate_reference_spec`. The script loads the target
package via `include_string` (stripping annotations first), evaluates the named function
on each generated input, and serializes a `Vector{NamedTuple}` of results to `output_path`.

Running in a separate process avoids module-name collisions between the reference package
and the submission package, and prevents student code from affecting the grader's state.
"""
function _reference_eval_script()
    return raw"""
using Serialization
using TOML

function _project_name(path::AbstractString)
    project = joinpath(path, "Project.toml")
    isfile(project) || error("Project.toml not found in " * path)
    data = TOML.parsefile(project)
    return String(get(data, "name", basename(path)))
end

function _call_with_input(f, input)
    input isa Tuple && return f(input...)
    return f(input)
end

function _collect_block(lines::AbstractVector, start_i::Int)
    body = String[]
    depth = 1
    i = start_i + 1
    while i <= length(lines)
        s = strip(lines[i])
        if endswith(s, " begin") || occursin(r"\bbegin\b", s)
            depth += count(==("begin"), split(s))
        end
        if s == "end"
            depth -= 1
            depth == 0 && return body, i
        end
        push!(body, lines[i])
        i += 1
    end
    error("unterminated annotation block beginning at line " * string(start_i))
end

function _keep_body(macro_name::AbstractString, mode::AbstractString)
    if mode == "student"
        return macro_name in ("@scaffolding", "@student_test")
    else
        return macro_name in ("@solution", "@student_test", "@hidden_test")
    end
end

function _loadable_source(text::AbstractString, mode::AbstractString)
    lines = split(text, '\n'; keepempty=true)
    out = String[]
    i = 1
    while i <= length(lines)
        stripped = strip(lines[i])
        if occursin(r"^(using|import)\s+SkeletonizePackage\b", stripped)
            i += 1
            continue
        elseif stripped in ("@solution begin", "@scaffolding begin", "@student_test begin", "@hidden_test begin")
            macro_name = split(stripped)[1]
            block, j = _collect_block(lines, i)
            _keep_body(macro_name, mode) && append!(out, block)
            i = j + 1
        else
            push!(out, lines[i])
            i += 1
        end
    end
    return join(out, "\n")
end

package_path = ARGS[1]
function_name = Symbol(ARGS[2])
input_expr = ARGS[3]
output_path = ARGS[4]
mode = ARGS[5]
grader_project = ARGS[6]
isempty(grader_project) || push!(LOAD_PATH, grader_project)
module_name = Symbol(_project_name(package_path))
source_path = joinpath(package_path, "src", string(module_name) * ".jl")
source = _loadable_source(read(source_path, String), mode)
include_string(Main, source, source_path)
mod = getfield(Main, module_name)
f = getfield(mod, function_name)
inputs = collect(eval(Meta.parse(input_expr)))
results = NamedTuple[]
for input in inputs
    try
        output = _call_with_input(f, input)
        push!(results, (ok=true, input=repr(input), output=repr(output), error=""))
    catch err
        push!(results, (ok=false, input=repr(input), output="", error=sprint(showerror, err)))
    end
end
serialize(output_path, results)
"""
end

function _rubric_points_by_category(items::Vector{RubricItem})
    points = Dict{String, Int}()
    for item in items
        item.kind in (:marks, :require, :forbid) || continue
        category = String(item.visibility)
        points[category] = get(points, category, 0) + item.points
    end
    return points
end

function _criterion_results(rubric::Vector{RubricItem}, property_results::Vector{PropertyCheckResult}, reference_results::Vector{ReferenceTestResult}, behavioral_passed::Bool, zeroed::Bool)
    results = CriterionResult[]
    property_queue = copy(property_results)
    for item in rubric
        if item.kind == :marks
            passed = behavioral_passed && !zeroed
            awarded = passed ? item.points : 0
            message = zeroed ? "assignment zeroed by a gating requirement" : passed ? "behavioural tests passed" : "behavioural tests failed"
            push!(results, CriterionResult(item.id, item.kind, item.visibility, item.points, awarded, item.description, passed, message, item.zero_marks))
        elseif item.kind in (:require, :forbid)
            result = isempty(property_queue) ? nothing : popfirst!(property_queue)
            passed = result !== nothing && result.passed && !zeroed
            awarded = passed ? item.points : 0
            message = result === nothing ? "property was not evaluated" : result.message
            zeroed && (message = "assignment zeroed by a gating requirement")
            push!(results, CriterionResult(item.id, item.kind, item.visibility, item.points, awarded, item.description, passed, message, item.zero_marks))
        elseif item.kind == :reference_test
            related = [result for result in reference_results if result.visibility == item.visibility]
            passed = !isempty(related) && all(result -> result.passed, related)
            message = isempty(related) ? "reference test metadata only" : passed ? "all generated inputs matched" : "one or more generated inputs failed"
            push!(results, CriterionResult(item.id, item.kind, item.visibility, item.points, 0, item.description, passed, message, item.zero_marks))
        end
    end
    return results
end

function _awarded_points_by_category(rubric::Vector{RubricItem}, criterion_results::Vector{CriterionResult})
    possible = _rubric_points_by_category(rubric)
    awarded = Dict(category => 0 for category in keys(possible))
    for result in criterion_results
        result.kind in (:marks, :require, :forbid) || continue
        category = String(result.visibility)
        awarded[category] = get(awarded, category, 0) + result.awarded
    end
    return awarded
end

function _student_grade_report(student_id::AbstractString, passed::Bool, exitcode::Int, rubric::Vector{RubricItem}, reference_results::Vector{ReferenceTestResult}, property_results::Vector{PropertyCheckResult}, criterion_results::Vector{CriterionResult}, awarded::Dict{String, Int}, possible::Dict{String, Int}, total_awarded::Int, total_possible::Int, stdout::String, stderr::String)
    io = IOBuffer()
    println(io, "# Student Feedback Report")
    println(io)
    isempty(student_id) || println(io, "Student: `", student_id, "`")
    println(io, "Status: ", passed ? "passed" : "failed")
    println(io, "Exit code: ", exitcode)
    println(io, "Total: ", total_awarded, " / ", total_possible, " marks")
    println(io)
    println(io, "## Mark Summary")
    categories = sort(collect(keys(possible)))
    if isempty(categories)
        println(io)
        println(io, "No marked rubric criteria were found in the reference package.")
    else
        println(io)
        for category in categories
            println(io, "- ", category, ": ", get(awarded, category, 0), " / ", possible[category])
        end
    end
    println(io)
    println(io, "## Rubric Results")
    marked_results = [result for result in criterion_results if result.kind in (:marks, :require, :forbid)]
    if isempty(marked_results)
        println(io)
        println(io, "No marked criteria were available.")
    else
        for result in marked_results
            println(io)
            zero_note = result.zero_marks ? " Zeroes assignment if failed." : ""
            println(io, "- `", result.id, "` [", result.visibility, "] ", result.description, ": ", result.awarded, " / ", result.points, " mark", result.points == 1 ? "" : "s", ". ", result.message, ".", zero_note)
        end
    end
    properties = [item for item in rubric if item.kind != :marks]
    if !isempty(properties)
        println(io)
        println(io, "## Code Properties")
        property_queue = copy(property_results)
        for item in properties
            println(io)
            if item.kind in (:require, :forbid) && !isempty(property_queue)
                result = popfirst!(property_queue)
                status = result.passed ? "passed" : "failed"
                points = result.passed ? result.points : 0
                zero_note = result.zero_marks ? " Zeroes assignment if failed." : ""
                println(io, "- [", result.visibility, "] ", status, ": ", result.description, " (", points, " / ", result.points, " marks).", zero_note)
            else
                println(io, "- [", item.visibility, "] ", item.description)
            end
        end
    end
    if !isempty(reference_results)
        println(io)
        println(io, "## Reference Tests")
        for result in reference_results
            status = result.passed ? "passed" : "failed"
            println(io)
            println(io, "- [", result.visibility, "] `", result.function_name, "` input ", result.index, " ", status, ": ", result.message)
        end
    end
    println(io)
    println(io, "## Test Output")
    if isempty(strip(stdout)) && isempty(strip(stderr))
        println(io)
        println(io, "No test output was captured.")
    else
        if !isempty(strip(stdout))
            println(io)
            println(io, "### stdout")
            println(io)
            println(io, "```text")
            print(io, rstrip(stdout))
            println(io)
            println(io, "```")
        end
        if !isempty(strip(stderr))
            println(io)
            println(io, "### stderr")
            println(io)
            println(io, "```text")
            print(io, rstrip(stderr))
            println(io)
            println(io, "```")
        end
    end
    return String(take!(io))
end

function _grade_csv(header_values::Vector{String}, row_values::Vector{String})
    header = join(_csv_escape.(header_values), ",")
    row = join(_csv_escape.(row_values), ",")
    return header, row
end

function _csv_escape(value::AbstractString)
    needs_quotes = any(ch -> ch in (',', '"', '\n', '\r'), value)
    escaped = replace(value, "\"" => "\"\"")
    return needs_quotes ? "\"$escaped\"" : escaped
end

function _write_grade_csv(path::AbstractString, header::AbstractString, row::AbstractString; append::Bool)
    should_write_header = !append || !isfile(path) || filesize(path) == 0
    open(path, append ? "a" : "w") do io
        should_write_header && println(io, header)
        println(io, row)
    end
    return path
end
