name: JET

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  jet:
    name: JET - Julia 1.12 - ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.12'
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - name: Run JET static analysis
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.activate(; temp=true)
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.add(PackageSpec(name="JET", version="0.11"))
          include(joinpath(pwd(), "test", "jet.jl"))
